# fly.toml app configuration file generated for zelax-properties-23443 on 2025-12-02T16:30:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zelax-properties-23443'
console_command = '/code/manage.py shell'
primary_region = 'jnb'

[build]

[deploy]
release_command = 'python manage.py migrate --noinput'

[env]
PORT = '8000'

[processes]
app = 'gunicorn --bind :8000 --workers 2 config.wsgi'
celery = 'celery -A config worker --loglevel=INFO'

[http_service]
auto_start_machines = true
auto_stop_machines = 'off'
force_https = true
internal_port = 8000
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
memory_mb = 1024

[[statics]]
guest_path = '/code/static'
url_prefix = '/static/'
